PREFIX : <https://joinup.ec.europa.eu/collection/rpam/1.1.0/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ccts: <http://www.unece.org/cefact#>

# USER STORY: I, as the CIO of our national central eMandate Registry, want to obtain the list of all the Mandates that have been registered in the Registry, so I can produce some statistic for accountability purposes.

select ?Mandate ?MandateId
FROM <https://joinup.ec.europa.eu/collection/rpam/1.1.0/ontology/mandates>
where {
	?Mandate a :Mandate ;
    :id [ccts:identifierValue ?MandateId] .
    bind (substr(?MandateId, 1, 4) as ?url) .
    filter (if(?url = "http", ?url, ?MandateId))
}
