PREFIX : <https://joinup.ec.europa.eu/collection/rpam/1.1.0/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ccts: <http://www.unece.org/cefact#>
PREFIX cc: <https://joinup.ec.europa.eu/collection/rpam/1.0.0/thesauri/countrycode#>
PREFIX ccev: <https://joinup.ec.europa.eu/collection/semic/ccev/2.0.3/ontology#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

# USER STORY: Constraints of Serge in SergeMandate-1

select ?Mandate ?Power ?MorConstraint ?ConstraintType
from <https://joinup.ec.europa.eu/collection/rpam/1.1.0/mandates#>
where {
    ?Mandate a  :Mandate ;
             	:mandator :Serge ;
             	:empowerment ?Power .
    ?Power :mandatorConstraint ?MorConstraint .
    ?MorConstraint ccev:type ?ConstraintType .

} order by ?Power