PREFIX : <https://joinup.ec.europa.eu/collection/rpam/1.1.0/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ccts: <http://www.unece.org/cefact#>
PREFIX cc: <https://joinup.ec.europa.eu/collection/rpam/1.0.0/thesauri/countrycode#>
PREFIX ccev: <https://joinup.ec.europa.eu/collection/semic/ccev/2.0.3/ontology#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ubl: <http://docs.oasis-open.org/ubl#>
PREFIX mee: <https://joinup.ec.europa.eu/collection/rpam/1.1.0/mandates#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ct: <https://joinup.ec.europa.eu/collection/rpam/1.0.0/thesauri/moremee#>

# USER STORY: All powers and constraints of Paula, regardless of the Mandator

    select distinct ?Mandator ?Power ?ConstraintType ?MEECONSTRAINT
    from mee:
	from ct:
    where {
        ?Mandate a  :Mandate ;
                 :mandator ?Mandator ;
                 :empowerment ?Power .
        ?Power :mandatee :Paula ;
               :mandateeConstraint ?MeeConstraint .
    	?MeeConstraint ccev:constraint ?MeeConstraintNode ; ccev:type ?ConstraintType .
    	?ConstraintType skos:definition ?def

        optional {?MeeConstraintNode ccev:datumCode [ccts:codeValue ?tu]}
        optional {?MeeConstraintNode ccev:datumIndicator ?osu}
        optional {?MeeConstraintNode ccev:datumPeriod [ubl:endDate ?endDate]}
        optional {?MeeConstraintNode ccev:datumAmount [ccts:amountValue ?ceil ; ccts:currencyID ?ceilCur]}
        optional {?MeeConstraintNode ccev:datumAmount [ccts:amountValue ?floor ; ccts:currencyID ?floorCur]}

    bind(if (str(?tu) != "", concat(str(?def),  ": ",  str(?tu)), "") as ?MEECONSTRAINT)
    bind(if (?osu, str(?def), "This power can be used repeatedly (more than once) while the power is valid.") as ?MEECONSTRAINT)
    bind(if (str(?ceil) !="", concat(str(?def), " ", str(?ceil), " ", ?ceilCur), "") as ?MEECONSTRAINT)
    bind(if (str(?endDate) !="", concat(str(?def),  ": ", str(?endDate)), "") as ?MEECONSTRAINT)
    }
